#!/bin/sh

## convertit les échantillons de questions en HTML

mkdir -p html_collection
rm -f html_collection/file* ## ôte des fichiers temporaires d'avant

tmpfile=$(tempfile -d html_collection)

cat beg $1 end > $tmpfile
wd=$(pwd)

cd html_collection
tf=$(basename $tmpfile)
htlatex $tf "" "" "" "--interaction=nonstopmode"

#if [ -f ${tf}.css ]; then
#    cp ${tf}.css common.css
#fi

ls ${tf}* | egrep -v '.*\.html' | xargs rm

if [ -f ${tf}.html ]; then
    sed 's/'$tf'\.css/common.css/' ${tf}.html > ${tf}.tmp && \
	mv ${tf}.tmp ${tf}.html
    mv ${tf}.html $(echo $(basename $1) | sed 's/tex$/html/')
fi
